#!/bin/bash

HELP="Open Vault frontend init script\n\n

USAGE:\n\n

  ./ov COMMAND [args] \n\n

COMMANDS:\n\n

\t  b | build \t  build the docker image\n
\t  c | cmd \t    run a bash command with the docker image\n
\t  d | dev \t    start a development server\n
\t  h | help \t   prints this help text\n
"

if [ -z $1 ]; then
  echo -e $HELP

elif [ $1 = "build" -o $1 = "b" ]; then
  shift
  docker build -t ov-front .

elif [ $1 = "cmd" -o $1 = "c" ]; then
  shift
  docker run -it \
    -v $(pwd):/var/app \
    ov-front "$@"

elif [ $1 = "dev" -o $1 = "d" ]; then
  shift
  docker run -it \
    -p 3000:3000 \
    -p 8002:8002 \
    -v $(pwd):/var/app \
    -e SECRET="super secret" \
    ov-front npm run dev

else
  echo "Unrecognized command"
  echo -e $HELP

fi
